{% set name = "raven-wps" %}
{% set version = "0.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ouranosinc/raven/archive/refs/tags/v{{ version }}.tar.gz
  sha256: db6ee7f1f9b8e10027e3cb4efcb2da5e30b26a56f3962bebb366a3ce37fdee9e

build:
  number: 1
#  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - raven-wps=raven.cli:cli
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python
    - pip
    - flit
  run:
    - python
    - pip
    - click
    - jinja2
    - matplotlib-base
    - netCDF4
    - numpy
    - owslib
    - pandas <2.0  # [py==38]
    - pandas  # [py>=39]
    - psutil
    - pywps ==4.5.1
    - requests
    - xarray >=0.18
    - xclim >=0.31.0
    # GIS libraries
    - affine
    - fiona >=1.9.0
    - geojson
    - geopandas
    - pyogrio
    - pyproj >=3.4
    - pysheds
    - rasterio
    - rasterstats
    - requests
    - rioxarray
    - shapely
    # Docs and other utilities
    - fsspec
    - psycopg2 # to use postgres to log pywps requests like in Prod
    - pymetalink
    - unidecode

# TODO: We need more tests here
test:
  requires:
    - make
    - pip
  source_files:
    - Makefile
  commands:
    - pip check
    - make start
    - sleep 2s
    - make stop

about:
  home: https://github.com/Ouranosinc/raven
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open source server project offering data collection and preparation, as well as geoprocessing and catchment delineation through the Web Processing Service (WPS) standard
  description: |
    Raven is an open source server project offering data collection and preparation,
    as well as geoprocessing and catchment delineation through the Web Processing
    Service (WPS) standard. Raven processes can be embedded in a graphical user
    interface or accessed directly from a programming environment. From Python,
    birdy WPSClient provides a user-friendly python interface to Raven's WPS
    processes for geospatial processing.
  doc_url: https://pavics-sdi.readthedocs.io/projects/raven/en/latest/
  dev_url: https://github.com/Ouranosinc/raven

extra:
  recipe-maintainers:
    - Zeitsperre
    - cjauvin
    - huard
